[package]
name = "wowie-jam-4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geng = { git = "https://github.com/kuviman/geng", version = "0.12.0" }
serde = "1.0.143"
